import {
  AlertTriangle,
  Lightbulb,
  BadgeAlert,
} from "lucide-react";

/* -------------------------------- */
/* Priority Badge                   */
/* -------------------------------- */

const PriorityBadge = ({ priority }) => {
  const styles = {
    High: "bg-red-50 text-red-600 border-red-100",
    Medium: "bg-amber-50 text-amber-600 border-amber-100",
    Low: "bg-emerald-50 text-emerald-600 border-emerald-100",
  };

  return (
    <span
      className={`
        px-2.5
        py-1
        rounded-full
        text-[11px]
        font-semibold
        border
        shrink-0
        ${styles[priority] || styles.Medium}
      `}
    >
      {priority || "Medium"}
    </span>
  );
};

/* -------------------------------- */
/* Improvement Tips                 */
/* -------------------------------- */

const ImprovementTips = ({ tips = [] }) => {
  return (
    <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6">

      {/* Header */}
      <div className="flex items-center gap-3 mb-5">

        <div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center shrink-0">
          <AlertTriangle
            size={19}
            className="text-orange-500"
          />
        </div>

        <div className="min-w-0">

          <h2 className="text-xl font-bold tracking-tight text-slate-900">
            Improvement Tips
          </h2>

          <p className="text-xs text-slate-500 mt-0.5">
            Personalized recommendations generated by AI
          </p>

        </div>

      </div>

      {/* Tips */}
      <div className="space-y-3">

        {tips.map((tip, index) => (

          <div
            key={index}
            className="
              rounded-2xl
              border
              border-slate-200
              p-4
              transition-all
              duration-200
              hover:border-indigo-200
              hover:shadow-sm
            "
          >

            {/* Top Section */}
            <div className="flex items-start justify-between gap-4">

              {/* Content */}
              <div className="flex gap-3 min-w-0">

                {/* Number */}
                <div
                  className="
                    w-8
                    h-8
                    rounded-lg
                    bg-indigo-600
                    text-white
                    flex
                    items-center
                    justify-center
                    text-sm
                    font-bold
                    shrink-0
                  "
                >
                  {index + 1}
                </div>

                {/* Text */}
                <div className="min-w-0">

                  <h3 className="text-sm font-semibold text-slate-800">
                    {tip.title}
                  </h3>

                  <p className="text-sm text-slate-600 leading-6 mt-1">
                    {tip.description}
                  </p>

                </div>

              </div>

              {/* Priority */}
              <PriorityBadge
                priority={tip.priority}
              />

            </div>

            {/* Example */}
            {tip.example && (
              <div
                className="
                  mt-3
                  rounded-xl
                  bg-slate-50
                  border
                  border-slate-100
                  px-3
                  py-2.5
                "
              >

                <div className="flex gap-2.5">

                  <Lightbulb
                    size={17}
                    className="text-amber-500 mt-0.5 shrink-0"
                  />

                  <div className="min-w-0">

                    <h4 className="text-xs font-semibold text-slate-700">
                      Example
                    </h4>

                    <p className="text-xs text-slate-600 leading-5 mt-0.5">
                      {tip.example}
                    </p>

                  </div>

                </div>

              </div>
            )}

          </div>

        ))}

      </div>

      {/* Practice Strategy */}
      <div
        className="
          mt-5
          rounded-2xl
          bg-indigo-50/70
          border
          border-indigo-100
          px-4
          py-3.5
        "
      >

        <div className="flex gap-3">

          <BadgeAlert
            size={18}
            className="text-indigo-600 mt-0.5 shrink-0"
          />

          <div>

            <h4 className="text-sm font-semibold text-slate-900">
              Practice Strategy
            </h4>

            <p className="text-xs text-slate-600 leading-5 mt-1">
              Focus on the{" "}
              <strong className="text-slate-800">
                High Priority
              </strong>{" "}
              suggestions first. Once they become natural, move to Medium
              and Low priority improvements. Consistent practice on one or
              two areas at a time leads to faster improvement.
            </p>

          </div>

        </div>

      </div>

    </div>
  );
};

export default ImprovementTips;