import {
  AlertTriangle,
  Lightbulb,
  BadgeAlert,
} from "lucide-react";

const PriorityBadge = ({ priority }) => {
  const styles = {
    High:
      "bg-red-100 text-red-700 border border-red-200",
    Medium:
      "bg-amber-100 text-amber-700 border border-amber-200",
    Low:
      "bg-emerald-100 text-emerald-700 border border-emerald-200",
  };

  return (
    <span
      className={`px-3 py-1 rounded-full text-xs font-semibold ${
        styles[priority] || styles.Medium
      }`}
    >
      {priority}
    </span>
  );
};

const ImprovementTips = ({ tips = [] }) => {
  return (
    <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-8">

      {/* Header */}

      <div className="flex items-center gap-3 mb-8">

        <div className="w-12 h-12 rounded-2xl bg-orange-50 flex items-center justify-center">

          <AlertTriangle
            size={22}
            className="text-orange-500"
          />

        </div>

        <div>

          <h2 className="text-3xl font-bold text-slate-900">
            Improvement Tips
          </h2>

          <p className="text-slate-500 mt-1">
            Personalized recommendations generated by AI
          </p>

        </div>

      </div>

      {/* Tips */}

      <div className="space-y-6">

        {tips.map((tip, index) => (

          <div
            key={index}
            className="rounded-2xl border border-slate-200 p-6 hover:border-indigo-200 transition"
          >

            {/* Top */}

            <div className="flex justify-between items-start">

              <div className="flex gap-4">

                <div className="w-11 h-11 rounded-xl bg-indigo-600 text-white flex items-center justify-center font-bold">

                  {index + 1}

                </div>

                <div>

                  <h3 className="text-xl font-semibold text-slate-800">

                    {tip.title}

                  </h3>

                  <p className="text-slate-600 mt-2 leading-7">

                    {tip.description}

                  </p>

                </div>

              </div>

              <PriorityBadge
                priority={tip.priority}
              />

            </div>

            {/* Example */}

            {tip.example && (

              <div className="mt-5 rounded-xl bg-slate-50 border border-slate-100 p-4">

                <div className="flex gap-3">

                  <Lightbulb
                    size={18}
                    className="text-amber-500 mt-1"
                  />

                  <div>

                    <h4 className="font-medium text-slate-800">

                      Example

                    </h4>

                    <p className="text-slate-600 leading-7 mt-1">

                      {tip.example}

                    </p>

                  </div>

                </div>

              </div>

            )}

          </div>

        ))}

      </div>

      {/* Footer */}

      <div className="mt-8 rounded-2xl bg-indigo-50 border border-indigo-100 p-5">

        <div className="flex gap-3">

          <BadgeAlert
            size={20}
            className="text-indigo-600 mt-1"
          />

          <div>

            <h4 className="font-semibold text-slate-900">

              Practice Strategy

            </h4>

            <p className="text-slate-600 leading-7 mt-2">

              Focus on completing the <strong>High Priority</strong> suggestions first.
              Once they become natural, move on to Medium and Low priority improvements.
              Consistent practice on one or two areas at a time leads to the fastest improvement.

            </p>

          </div>

        </div>

      </div>

    </div>
  );
};

export default ImprovementTips;